### ISSUE TITLE
哥们好

### ISSUE THREAD

**Issue by xiaopohou** [a312586670/IdentityServerDemo#1]
感谢你的分享，给你一个大赞，请问：
Asp.Net Core IdentityServer4 的各种应用
Dapper 的实践应用
微服务的实践应用
服务发现的实践应用
Overt.Core.Grpc 开源微服务框架实践
Overt.Core.Data Dapper 开源框架的实践
DDD 领域驱动的实践
消息队列
.Net Core 虚拟化
Redis
Mongodb
ES
K8S
等其他实践技术，待定

这些你完成了哪些呢？我想拉取一下git,跟着大佬进步

**Comment by e-jlion** [comment]
同步我的博客文章，目前博客文章还会继续分析IdentityServer4 的各种实战和源码的解读及原理探索，更新不会那么快，微服务初步实践的目前已经提交，其他的还带跟着我的博客文章分享出来，感谢支持
