### ISSUE TITLE
下载后运行报错”ServiceID missing“

### ISSUE THREAD

**Issue by qixianlqx** [a312586670/IdentityServerDemo#2]
你好！
看贵源码运行调试出现一个问题，详情如下：
1、下载代码后运行，出现”ServiceID missing“的错误，其实真正的错误是”Request decode failed: json: unknown field "ID“;
2、跟踪到Overt.Core.Grpc源码发现是由于ServerRegister类中RegisterService方法注册服务时用了AgentCheckRegistration继承了AgentServiceCheck，加了ID字段导致，而直接使用AgentServiceCheck则正常；
不知道是本地哪里配置问题导致，还是哪个包不对导致，还请指正！

**Comment by e-jlion** [comment]
你运行哪个出现的这个错误

**Comment by e-jlion** [comment]
你把appsettings.json 配置发我看下

**Comment by qixianlqx** [comment]
运行 Jlion.NetCore.OrderService
发现配置 http://47.98.133.8:8500/ 你这个正常，配置本地的就报错，难道是本地的consul版本问题？
consulsettings.json ：
{
  "ConsulServer": {
    "Service": {
      "Address": "http://127.0.0.1:8500/" // Consul 服务发现配置地址
    }
  }
}
appsettings.json：
{
  "GrpcServer": {
    "Service": {
      "Name": "JlionOrderService",
      "Port": 10001,
      "HostEnv": "serviceaddress",
      "Consul": {
        "Path": "dllconfigs/consulsettings.json"
      }
    }
  }
}

**Comment by e-jlion** [comment]
你用的Consul是哪个版本，我研究下，一直没遇到过你这个问题

**Comment by qixianlqx** [comment]
1.7.2版本

**Comment by e-jlion** [comment]
加这个QQ 群 1083147206 开源作者在里面，可以在这里面询问，可能时版本问题，demo中consul 地址是 1.6.x的 版本，我晚上试一下1.7.2 版本

**Comment by mojinxun** [comment]
overt.core.grpc 升级为：1.0.3.1即可支持新版本的Consul @qixianlqx @a312586670

**Comment by qixianlqx** [comment]
好的，谢谢！

**Comment by e-jlion** [comment]
Demo 中 overt.core.grpc 已经升级到1.0.3.1
